# https://docs.microsoft.com/vsts/pipelines/languages/xamarin
jobs:

- job: AutomatedTests
  pool:
    VMImage: 'windows-2019'
  steps:
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**'
      searchFolder: '$(System.DefaultWorkingDirectory)'

- job: Android
  pool:
    vmImage: 'windows-2019'
  variables:
    buildConfiguration: 'Debug'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'
      #msbuildArchitectureOption: x64
      #createAppPackage: true
      msbuildArguments: /p:JavaSdkDirectory="$(JAVA_HOME)/"

#- job: iOS
#  pool:
#    vmImage: 'macOS-10.14'
#  variables:
#    buildConfiguration: 'Debug'
#  steps:
#  - task: NuGetToolInstaller@0
#  - task: NuGetCommand@2
#    inputs:
#      restoreSolution: '**/*.sln'
#  - task: XamariniOS@2
#    inputs:
#      clean: true
#      runNugetRestore: true
#      solutionFile: '**/*iOS.csproj'
#      configuration: '$(buildConfiguration)'
#      buildForSimulator: true
#      packageApp: false