// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace MSC.ConferenceMate.DTO.CM
{
	public partial class User
	{
		public User()
		{
			InitializePartial();
		}

		public int UserId { get; set; } // Primary key
		public string UserName { get; set; }
		public string Email { get; set; }
		public System.DateTime? BirthDate { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public int GenderTypeId { get; set; }
		public string Password { get; set; }
		public string Salt { get; set; }
		public System.DateTime LastLogin { get; set; }
		public int PreferredLanguageId { get; set; }
		public string Biography { get; set; }
		public string PhotoUrl { get; set; }
		public string AvatarUrl { get; set; }
		public string CompanyName { get; set; }
		public string JobTitle { get; set; }
		public string CompanyWebsiteUrl { get; set; }
		public string BlogUrl { get; set; }
		public string TwitterUrl { get; set; }
		public string LinkedInUrl { get; set; }
		public int DataVersion { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string ModifiedBy { get; set; }
		public bool IsDeleted { get; set; }
		// public virtual System.Collections.Generic.ICollection<Feedback> Feedbacks { get; set; } // Many to many mapping -- Excluded navigation property per configuration.
		public virtual System.Collections.Generic.ICollection<SessionLike> SessionLikes { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.ICollection<SessionSpeaker> SessionSpeakers { get; set; } // Many to many mapping
		public virtual GenderType GenderType { get; set; } 
		public virtual LanguageType LanguageType { get; set; } 


		partial void InitializePartial();

	}
}
