// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class UserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
    {
        public UserConfiguration()
            : this("dbo")
        {
        }

        public UserConfiguration(string schema)
        {
            ToTable("Users", schema);
            HasKey(x => x.UserId);

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.BirthDate).HasColumnName(@"BirthDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.GenderTypeId).HasColumnName(@"GenderTypeId").HasColumnType("int").IsRequired();
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Salt).HasColumnName(@"Salt").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.LastLogin).HasColumnName(@"LastLogin").HasColumnType("datetime2").IsRequired();
            Property(x => x.PreferredLanguageId).HasColumnName(@"PreferredLanguageId").HasColumnType("int").IsRequired();
            Property(x => x.Biography).HasColumnName(@"Biography").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.PhotoUrl).HasColumnName(@"PhotoUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.AvatarUrl).HasColumnName(@"AvatarUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.JobTitle).HasColumnName(@"JobTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.CompanyWebsiteUrl).HasColumnName(@"CompanyWebsiteUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.BlogUrl).HasColumnName(@"BlogUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.TwitterUrl).HasColumnName(@"TwitterUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.LinkedInUrl).HasColumnName(@"LinkedInUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.DataVersion).HasColumnName(@"DataVersion").HasColumnType("int").IsRequired();
            Property(x => x.CreatedUtcDate).HasColumnName(@"CreatedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.ModifiedUtcDate).HasColumnName(@"ModifiedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.GenderType).WithMany(b => b.Users).HasForeignKey(c => c.GenderTypeId).WillCascadeOnDelete(false); // FK_Users_GenderType_GenderTypeId
            HasRequired(a => a.LanguageType).WithMany(b => b.Users).HasForeignKey(c => c.PreferredLanguageId).WillCascadeOnDelete(false); // FK_Users_LanguageType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
