// <auto-generated> - Template:MapperSqliteModelDataToMvvmLightModelObject, Version:1.1, Id:ec39b410-017a-407f-be75-0cf4fd66efd2
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using objCM = MSC.CM.Xam.ModelObj.CM;
using dataCM = MSC.CM.Xam.ModelData.CM;

namespace MSC.CM.Xam
{
	public static partial class ModelMapper
	{

		#region ModelObj to ModelData

		public static dataCM.Announcement ToModelData(this objCM.Announcement source)
		{
			return new dataCM.Announcement()
			{
				AnnouncementId = source.AnnouncementId,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				EndTime = source.EndTime,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ShortTitle = source.ShortTitle,
				StartTime = source.StartTime,
				Title = source.Title,
			};
		}

		public static dataCM.FeaturedEvent ToModelData(this objCM.FeaturedEvent source)
		{
			return new dataCM.FeaturedEvent()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				EndTime = source.EndTime,
				FeaturedEventId = source.FeaturedEventId,
				IsAllDay = source.IsAllDay,
				IsDeleted = source.IsDeleted,
				Location = source.Location,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ShortTitle = source.ShortTitle,
				StartTime = source.StartTime,
				Title = source.Title,
			};
		}

		public static dataCM.Feedback ToModelData(this objCM.Feedback source)
		{
			return new dataCM.Feedback()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				Dispositioned = source.Dispositioned,
				FeaturedEventId = source.FeaturedEventId,
				FeedbackId = source.FeedbackId,
				FeedbackInitiatorTypeId = source.FeedbackInitiatorTypeId,
				FeedbackTypeId = source.FeedbackTypeId,
				IsChat = source.IsChat,
				IsDeleted = source.IsDeleted,
				IsPublic = source.IsPublic,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RatingValue = source.RatingValue,
				SessionId = source.SessionId,
				Source = source.Source,
				Title = source.Title,
				UserId = source.UserId,
			};
		}

		public static dataCM.FeedbackInitiatorType ToModelData(this objCM.FeedbackInitiatorType source)
		{
			return new dataCM.FeedbackInitiatorType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				FeedbackInitiatorTypeId = source.FeedbackInitiatorTypeId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataCM.FeedbackType ToModelData(this objCM.FeedbackType source)
		{
			return new dataCM.FeedbackType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				FeedbackTypeId = source.FeedbackTypeId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataCM.GenderType ToModelData(this objCM.GenderType source)
		{
			return new dataCM.GenderType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataCM.LanguageType ToModelData(this objCM.LanguageType source)
		{
			return new dataCM.LanguageType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageCultureIdentifier = source.LanguageCultureIdentifier,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NativeName = source.NativeName,
				ThreeLetterIsoLanguageName = source.ThreeLetterIsoLanguageName,
				TwoLetterIsoLanguageName = source.TwoLetterIsoLanguageName,
			};
		}

		public static dataCM.LookupList ToModelData(this objCM.LookupList source)
		{
			return new dataCM.LookupList()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				CustomJson = source.CustomJson,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				ForeignKeyTableName = source.ForeignKeyTableName,
				ForeignKeyTablePkId = source.ForeignKeyTablePkId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				LookupListId = source.LookupListId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static dataCM.Room ToModelData(this objCM.Room source)
		{
			return new dataCM.Room()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RoomId = source.RoomId,
				SeatingCapacity = source.SeatingCapacity,
				ShortTitle = source.ShortTitle,
				Title = source.Title,
			};
		}

		public static dataCM.Session ToModelData(this objCM.Session source)
		{
			return new dataCM.Session()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				EndTime = source.EndTime,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RoomId = source.RoomId,
				SessionId = source.SessionId,
				ShortTitle = source.ShortTitle,
				StartTime = source.StartTime,
				Title = source.Title,
			};
		}

		public static dataCM.SessionCategoryType ToModelData(this objCM.SessionCategoryType source)
		{
			return new dataCM.SessionCategoryType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Name = source.Name,
				SessionCategoryTypeId = source.SessionCategoryTypeId,
			};
		}

		public static dataCM.SessionLike ToModelData(this objCM.SessionLike source)
		{
			return new dataCM.SessionLike()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SessionId = source.SessionId,
				UserId = source.UserId,
			};
		}

		public static dataCM.SessionSessionCategoryType ToModelData(this objCM.SessionSessionCategoryType source)
		{
			return new dataCM.SessionSessionCategoryType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SessionCategoryTypeId = source.SessionCategoryTypeId,
				SessionId = source.SessionId,
			};
		}

		public static dataCM.SessionSpeaker ToModelData(this objCM.SessionSpeaker source)
		{
			return new dataCM.SessionSpeaker()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SessionId = source.SessionId,
				UserId = source.UserId,
                SessionIdUserId = $"{source.SessionId}{source.UserId}"

            };
		}

		public static dataCM.Sponsor ToModelData(this objCM.Sponsor source)
		{
			return new dataCM.Sponsor()
			{
				BoothLocation = source.BoothLocation,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				ImageUrl = source.ImageUrl,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Rank = source.Rank,
				ShortTitle = source.ShortTitle,
				SponsorId = source.SponsorId,
				SponsorTypeId = source.SponsorTypeId,
				Title = source.Title,
				TwitterUrl = source.TwitterUrl,
				WebsiteUrl = source.WebsiteUrl,
			};
		}

		public static dataCM.SponsorFeaturedEvent ToModelData(this objCM.SponsorFeaturedEvent source)
		{
			return new dataCM.SponsorFeaturedEvent()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				FeaturedEventId = source.FeaturedEventId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SponsorId = source.SponsorId,
			};
		}

		public static dataCM.SponsorType ToModelData(this objCM.SponsorType source)
		{
			return new dataCM.SponsorType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SponsorTypeId = source.SponsorTypeId,
			};
		}

		public static dataCM.User ToModelData(this objCM.User source)
		{
			return new dataCM.User()
			{
				AvatarUrl = source.AvatarUrl,
				Biography = source.Biography,
				BirthDate = source.BirthDate,
				BlogUrl = source.BlogUrl,
				CompanyName = source.CompanyName,
				CompanyWebsiteUrl = source.CompanyWebsiteUrl,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Email = source.Email,
				FirstName = source.FirstName,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				JobTitle = source.JobTitle,
				LastLogin = source.LastLogin,
				LastName = source.LastName,
				LinkedInUrl = source.LinkedInUrl,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Password = source.Password,
				PhotoUrl = source.PhotoUrl,
				PreferredLanguageId = source.PreferredLanguageId,
				Salt = source.Salt,
				TwitterUrl = source.TwitterUrl,
				UserId = source.UserId,
				UserName = source.UserName,
			};
		}


		#endregion ModelObj to ModelData

		#region ModelData to ModelObj

		public static objCM.Announcement ToModelObj(this dataCM.Announcement source)
		{
			return new objCM.Announcement()
			{
				AnnouncementId = source.AnnouncementId,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				EndTime = source.EndTime,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ShortTitle = source.ShortTitle,
				StartTime = source.StartTime,
				Title = source.Title,
			};
		}

		public static objCM.FeaturedEvent ToModelObj(this dataCM.FeaturedEvent source)
		{
			return new objCM.FeaturedEvent()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				EndTime = source.EndTime,
				FeaturedEventId = source.FeaturedEventId,
				IsAllDay = source.IsAllDay,
				IsDeleted = source.IsDeleted,
				Location = source.Location,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				ShortTitle = source.ShortTitle,
				StartTime = source.StartTime,
				Title = source.Title,
			};
		}

		public static objCM.Feedback ToModelObj(this dataCM.Feedback source)
		{
			return new objCM.Feedback()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				Dispositioned = source.Dispositioned,
				FeaturedEventId = source.FeaturedEventId,
				FeedbackId = source.FeedbackId,
				FeedbackInitiatorTypeId = source.FeedbackInitiatorTypeId,
				FeedbackTypeId = source.FeedbackTypeId,
				IsChat = source.IsChat,
				IsDeleted = source.IsDeleted,
				IsPublic = source.IsPublic,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RatingValue = source.RatingValue,
				SessionId = source.SessionId,
				Source = source.Source,
				Title = source.Title,
				UserId = source.UserId,
			};
		}

		public static objCM.FeedbackInitiatorType ToModelObj(this dataCM.FeedbackInitiatorType source)
		{
			return new objCM.FeedbackInitiatorType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				FeedbackInitiatorTypeId = source.FeedbackInitiatorTypeId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objCM.FeedbackType ToModelObj(this dataCM.FeedbackType source)
		{
			return new objCM.FeedbackType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				FeedbackTypeId = source.FeedbackTypeId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objCM.GenderType ToModelObj(this dataCM.GenderType source)
		{
			return new objCM.GenderType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objCM.LanguageType ToModelObj(this dataCM.LanguageType source)
		{
			return new objCM.LanguageType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				IsDeleted = source.IsDeleted,
				LanguageCultureIdentifier = source.LanguageCultureIdentifier,
				LanguageTypeId = source.LanguageTypeId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				NativeName = source.NativeName,
				ThreeLetterIsoLanguageName = source.ThreeLetterIsoLanguageName,
				TwoLetterIsoLanguageName = source.TwoLetterIsoLanguageName,
			};
		}

		public static objCM.LookupList ToModelObj(this dataCM.LookupList source)
		{
			return new objCM.LookupList()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				CustomJson = source.CustomJson,
				DataVersion = source.DataVersion,
				Description = source.Description,
				DisplayPriority = source.DisplayPriority,
				DisplayText = source.DisplayText,
				ForeignKeyTableName = source.ForeignKeyTableName,
				ForeignKeyTablePkId = source.ForeignKeyTablePkId,
				IsDeleted = source.IsDeleted,
				LanguageTypeId = source.LanguageTypeId,
				LookupListId = source.LookupListId,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
			};
		}

		public static objCM.Room ToModelObj(this dataCM.Room source)
		{
			return new objCM.Room()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				IsDeleted = source.IsDeleted,
				Latitude = source.Latitude,
				Longitude = source.Longitude,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RoomId = source.RoomId,
				SeatingCapacity = source.SeatingCapacity,
				ShortTitle = source.ShortTitle,
				Title = source.Title,
			};
		}

		public static objCM.Session ToModelObj(this dataCM.Session source)
		{
			return new objCM.Session()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				EndTime = source.EndTime,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				RoomId = source.RoomId,
				SessionId = source.SessionId,
				ShortTitle = source.ShortTitle,
				StartTime = source.StartTime,
				Title = source.Title,
			};
		}

		public static objCM.SessionCategoryType ToModelObj(this dataCM.SessionCategoryType source)
		{
			return new objCM.SessionCategoryType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Name = source.Name,
				SessionCategoryTypeId = source.SessionCategoryTypeId,
			};
		}

		public static objCM.SessionLike ToModelObj(this dataCM.SessionLike source)
		{
			return new objCM.SessionLike()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SessionId = source.SessionId,
				UserId = source.UserId,
			};
		}

		public static objCM.SessionSessionCategoryType ToModelObj(this dataCM.SessionSessionCategoryType source)
		{
			return new objCM.SessionSessionCategoryType()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SessionCategoryTypeId = source.SessionCategoryTypeId,
				SessionId = source.SessionId,
			};
		}

		public static objCM.SessionSpeaker ToModelObj(this dataCM.SessionSpeaker source)
		{
			return new objCM.SessionSpeaker()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SessionId = source.SessionId,
				UserId = source.UserId,
			};
		}

		public static objCM.Sponsor ToModelObj(this dataCM.Sponsor source)
		{
			return new objCM.Sponsor()
			{
				BoothLocation = source.BoothLocation,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Description = source.Description,
				ImageUrl = source.ImageUrl,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Rank = source.Rank,
				ShortTitle = source.ShortTitle,
				SponsorId = source.SponsorId,
				SponsorTypeId = source.SponsorTypeId,
				Title = source.Title,
				TwitterUrl = source.TwitterUrl,
				WebsiteUrl = source.WebsiteUrl,
			};
		}

		public static objCM.SponsorFeaturedEvent ToModelObj(this dataCM.SponsorFeaturedEvent source)
		{
			return new objCM.SponsorFeaturedEvent()
			{
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				FeaturedEventId = source.FeaturedEventId,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SponsorId = source.SponsorId,
			};
		}

		public static objCM.SponsorType ToModelObj(this dataCM.SponsorType source)
		{
			return new objCM.SponsorType()
			{
				Code = source.Code,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				IsDeleted = source.IsDeleted,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				SponsorTypeId = source.SponsorTypeId,
			};
		}

		public static objCM.User ToModelObj(this dataCM.User source)
		{
			return new objCM.User()
			{
				AvatarUrl = source.AvatarUrl,
				Biography = source.Biography,
				BirthDate = source.BirthDate,
				BlogUrl = source.BlogUrl,
				CompanyName = source.CompanyName,
				CompanyWebsiteUrl = source.CompanyWebsiteUrl,
				CreatedBy = source.CreatedBy,
				CreatedUtcDate = source.CreatedUtcDate,
				DataVersion = source.DataVersion,
				Email = source.Email,
				FirstName = source.FirstName,
				GenderTypeId = source.GenderTypeId,
				IsDeleted = source.IsDeleted,
				JobTitle = source.JobTitle,
				LastLogin = source.LastLogin,
				LastName = source.LastName,
				LinkedInUrl = source.LinkedInUrl,
				ModifiedBy = source.ModifiedBy,
				ModifiedUtcDate = source.ModifiedUtcDate,
				Password = source.Password,
				PhotoUrl = source.PhotoUrl,
				PreferredLanguageId = source.PreferredLanguageId,
				Salt = source.Salt,
				TwitterUrl = source.TwitterUrl,
				UserId = source.UserId,
				UserName = source.UserName,
			};
		}


		#endregion ModelData to ModelObj

	}
}
