// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoSession
	{
		public static int SampleSessionId0000 = 1671307271;
		public static int SampleSessionId0100 = 2049792612;
        public static int SampleSessionId0200 = 1671307273;
        public static int SampleSessionId0300 = 2049792614;
        public static int SampleSessionId0400 = 1671307275;
        public static int SampleSessionId0500 = 2049792616;

        public static Session SampleSession00
		{
			get
			{
				return new Session()
				{
					SessionId = SampleSessionId0000,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					RoomId = DemoRoom.SampleRoomId0000,
					StartTime = DateTime.Now,
					EndTime = DateTime.Now,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static Session SampleSession01
		{
			get
			{
				return new Session()
				{
					SessionId = SampleSessionId0100,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					RoomId = DemoRoom.SampleRoomId0000,
					StartTime = DateTime.Now,
					EndTime = DateTime.Now,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

        public static Session SampleSession02
        {
            get
            {
                return new Session()
                {
                    SessionId = SampleSessionId0200,
                    Title = "SampleTitle",
                    ShortTitle = "SampleShortTitle",
                    Description = "SampleDescription",
                    RoomId = DemoRoom.SampleRoomId0000,
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    DataVersion = 0,
                    CreatedUtcDate = DateTime.Now,
                    CreatedBy = "SampleCreatedBy",
                    ModifiedUtcDate = DateTime.Now,
                    ModifiedBy = "SampleModifiedBy",
                    IsDeleted = false,
                };
            }
        }
        public static Session SampleSession03
        {
            get
            {
                return new Session()
                {
                    SessionId = SampleSessionId0300,
                    Title = "SampleTitle",
                    ShortTitle = "SampleShortTitle",
                    Description = "SampleDescription",
                    RoomId = DemoRoom.SampleRoomId0100,
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    DataVersion = 0,
                    CreatedUtcDate = DateTime.Now,
                    CreatedBy = "SampleCreatedBy",
                    ModifiedUtcDate = DateTime.Now,
                    ModifiedBy = "SampleModifiedBy",
                    IsDeleted = false,
                };
            }
        }

        public static Session SampleSession04
        {
            get
            {
                return new Session()
                {
                    SessionId = SampleSessionId0400,
                    Title = "SampleTitle",
                    ShortTitle = "SampleShortTitle",
                    Description = "SampleDescription",
                    RoomId = RoomId = DemoRoom.SampleRoomId0100,
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    DataVersion = 0,
                    CreatedUtcDate = DateTime.Now,
                    CreatedBy = "SampleCreatedBy",
                    ModifiedUtcDate = DateTime.Now,
                    ModifiedBy = "SampleModifiedBy",
                    IsDeleted = false,
                };
            }
        }
        public static Session SampleSession05
        {
            get
            {
                return new Session()
                {
                    SessionId = SampleSessionId0500,
                    Title = "SampleTitle",
                    ShortTitle = "SampleShortTitle",
                    Description = "SampleDescription",
                    RoomId = RoomId = DemoRoom.SampleRoomId0100,
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    DataVersion = 0,
                    CreatedUtcDate = DateTime.Now,
                    CreatedBy = "SampleCreatedBy",
                    ModifiedUtcDate = DateTime.Now,
                    ModifiedBy = "SampleModifiedBy",
                    IsDeleted = false,
                };
            }
        }

    }
}
