// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using MSC.ConferenceMate.API.Client.Interface;
using MSC.ConferenceMate.Model.CM.Interface;
using xDTO = MSC.ConferenceMate.DTO.CM;

namespace MSC.ConferenceMate.Model.CM
{

	public class LoadRequestUser : EventArgs
	{
		public LoadRequestUser(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class User : BaseModel<IWebApiDataServiceCM>, IUser
	{
		public event EventHandler<LoadRequestUser> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.User _dto = null;

		public User(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService) : base(log, dataService)
		{
			_dto = new xDTO.User();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public User(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService, xDTO.User dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string AvatarUrl { get { return _dto.AvatarUrl; } }
		public virtual string Biography { get { return _dto.Biography; } }
		public virtual System.DateTime? BirthDate { get { return _dto.BirthDate; } }
		public virtual string BlogUrl { get { return _dto.BlogUrl; } }
		public virtual string CompanyName { get { return _dto.CompanyName; } }
		public virtual string CompanyWebsiteUrl { get { return _dto.CompanyWebsiteUrl; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual string Email { get { return _dto.Email; } }
		public virtual string FirstName { get { return _dto.FirstName; } }
		public virtual int GenderTypeId { get { return _dto.GenderTypeId; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string JobTitle { get { return _dto.JobTitle; } }
		public virtual System.DateTime LastLogin { get { return _dto.LastLogin; } }
		public virtual string LastName { get { return _dto.LastName; } }
		public virtual string LinkedInUrl { get { return _dto.LinkedInUrl; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual string Password { get { return _dto.Password; } }
		public virtual string PhotoUrl { get { return _dto.PhotoUrl; } }
		public virtual int PreferredLanguageId { get { return _dto.PreferredLanguageId; } }
		public virtual string Salt { get { return _dto.Salt; } }
		public virtual string TwitterUrl { get { return _dto.TwitterUrl; } }
		public virtual int UserId { get { return _dto.UserId; } }
		public virtual string UserName { get { return _dto.UserName; } }

		private IGenderType _genderType = null; // Foreign Key
		private ILanguageType _languageType = null; // Foreign Key
		private List<IFeedback> _feedbacks = null; // Reverse Navigation
		private List<ISessionLike> _sessionLikes = null; // Reverse Navigation
		private List<ISessionSpeaker> _sessionSpeakers = null; // Reverse Navigation


		public virtual IGenderType GenderType
		{
			get
			{
				if (_genderType == null && _dto != null && _dto.GenderType != null)
				{
					_genderType = new GenderType(Log, DataService, _dto.GenderType);
				}

				return _genderType;
			}
		}

		public virtual ILanguageType LanguageType
		{
			get
			{
				if (_languageType == null && _dto != null && _dto.LanguageType != null)
				{
					_languageType = new LanguageType(Log, DataService, _dto.LanguageType);
				}

				return _languageType;
			}
		}

		public virtual List<IFeedback> Feedbacks
		{
			get
			{
				if (_feedbacks == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Feedbacks)));
				}

				return _feedbacks;
			}
		}

		public virtual List<ISessionLike> SessionLikes
		{
			get
			{
				if (_sessionLikes == null && _dto != null)
				{	// The core DTO object is loaded, but this property is not loaded.
					if (_dto.SessionLikes != null)
					{	// The core DTO object has data for this property, load it into the model.
						_sessionLikes = new List<ISessionLike>();
						foreach (var dtoItem in _dto.SessionLikes)
						{
							_sessionLikes.Add(new SessionLike(Log, DataService, dtoItem));
						}
					}
					else
					{	// Trigger the load data request - The core DTO object is loaded and does not have data for this property.
						OnLazyLoadRequest(this, new LoadRequestUser(nameof(SessionLikes)));
					}
				}

				return _sessionLikes;
			}
		}

		public virtual List<ISessionSpeaker> SessionSpeakers
		{
			get
			{
				if (_sessionSpeakers == null && _dto != null)
				{	// The core DTO object is loaded, but this property is not loaded.
					if (_dto.SessionSpeakers != null)
					{	// The core DTO object has data for this property, load it into the model.
						_sessionSpeakers = new List<ISessionSpeaker>();
						foreach (var dtoItem in _dto.SessionSpeakers)
						{
							_sessionSpeakers.Add(new SessionSpeaker(Log, DataService, dtoItem));
						}
					}
					else
					{	// Trigger the load data request - The core DTO object is loaded and does not have data for this property.
						OnLazyLoadRequest(this, new LoadRequestUser(nameof(SessionSpeakers)));
					}
				}

				return _sessionSpeakers;
			}
		}



	}
}
