// <auto-generated> - Template:APIStatusController, Version:1.1, Id:a5d78309-5a18-4a09-9225-03e602b52187
using System;
using System.Threading.Tasks;
using System.Web.Http;
using CodeGenHero.WebApi;
using CodeGenHero.Logging;
using MSC.ConferenceMate.Repository.Interface;
using MSC.ConferenceMate.Web.Infrastructure;

namespace MSC.ConferenceMate.API.Controllers.CM
{
	public partial class CMUserSecurityController : CMBaseApiController
	{
		readonly ISession _session;

		public CMUserSecurityController()
		{
			throw new ApplicationException($"Use of parameterless constructor when the IoC container should have used the contstructor with more parameters.");
		}

		public CMUserSecurityController(ILoggingService log, ICMRepository repository, ISession session)
			: base(log, repository)
		{
			_session = session;
		}

		[HttpGet]
		[VersionedRoute(template: "UserSecurity", allowedVersion: 1, Name = "CMUserSecurity")]
		public async Task<IHttpActionResult> Get()
		{
			try
			{
				var version = this.GetType().Assembly.GetName().Version;
				return Ok(version);
			}
			catch (Exception ex)
			{
				Error(message: ex.Message, logMessageType: LogMessageType.Instance.Exception_WebApi, ex: ex);

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}
	}
}
